### ISSUE TITLE
feature request: state with raw data

### ISSUE THREAD

**Issue by hombach** [hombach/ioBroker.teslafi#26]
<lars> -  was noch cool wäre:
in info, ein Objekt JSON, in den du einfach hart das letzte empfangene JSON schreibst. das man damit recht einfach sehen kann was er aktuell empfängt. also komplett ohne weitere Bearbeitung.

**Comment by Enno-von-Schwerin** [comment]
Test okay
RAW data will be written into object rawJSON

Thanks.

**Comment by hombach** [comment]
0.2.0 released to NPM
