### ISSUE TITLE
feature request: add values "seat_heater....."

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#30]
please add all 5 values: "Seat_heater..." to the objects read from teslafi_API

because i will automate my car heating based on outside / inside temprature and home office / office
and with these stats i can check if the command -> start seat heating was successfull

**Comment by hombach** [comment]
so, all without seats without "seat_heater_rear_left_back" and "seat_heater_rear_right_back" from Model X ... ?

**Comment by Enno-von-Schwerin** [comment]
if you can add all, please add 3rd row as well.
because MY will have a 3rd row in near future.
and maybe a user will appreciate these values.

**Comment by hombach** [comment]
Let's do so....
but are the third row seats in 7-seater Model Y are heated? Not sure about that...

**Comment by Enno-von-Schwerin** [comment]
![image](https://github.com/user-attachments/assets/ff8291bc-fbe2-4824-8c8a-84eb76637b0e)
The App idicates that seat heating is available for 7seater Model Y on all 7 seats.

**Comment by Enno-von-Schwerin** [comment]
and maybe you can also add stearing wheel heating?
my old car didn´t have these feature, so i always forget about this.

**Comment by hombach** [comment]
API get's us the power that is choosen and if the seat is available:

"seat_heater_rear_right": "3",
"seat_heater_rear_left_back": "",
"seat_heater_left": "2",

0: OFF
1: level 1
2: level 2
3: level 3
"": not present

how to deal with that?
"" or not present will end in not generating a state at all....
but what data type is best? Boolean? ON/OFF
or an number value 0 to 3?
or  string value like 
0: OFF
1: level 1
2: level 2
3: level 3

???

**Comment by Enno-von-Schwerin** [comment]
number value
a) you can send the command 
command=seat_heater&heater=X&level=X
Heater: 0-Driver, 1-Passenger, 2-Rear Left, 4-Rear Center, 5-Rear Right
Level: 0-3 (0 is off)
and if you put the vlaue as a number in, we can check if the command was successfull and which level is activated.
b) "" = not present
good question.
not generating the state or generating the state and put -1 in as "not present"
I think it´s up to you. and best practice.

**Comment by hombach** [comment]
implemented in 0.2.0

**Comment by Enno-von-Schwerin** [comment]
found a value in teslafi API:

,"third_row_seats":null

maybe you could add 3rd row seat heater only if 3rd row seats are available?

**Comment by hombach** [comment]
good point!

**Comment by Enno-von-Schwerin** [comment]
But who knows? It´s a Tesla. Maybe they will add 3rd row seats for free with the next Holiday OTA Update. 🤣

**Comment by hombach** [comment]
Possible - but then seat heater will be available at least as paid update

**Comment by hombach** [comment]
0.2.0 released to NPM
