### ISSUE TITLE
feature request: "driver_temp_setting"

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#31]
please add value: "driver_temp_setting" to the objects read from teslafi_API

because i will automate my car heating based on outside / inside temprature and home office / office
and with these stats i can check if the command -> start heating was successfull and to which temp the car will heat

**Comment by hombach** [comment]
implemented in 0.2.0

**Comment by Enno-von-Schwerin** [comment]
Test okay

value is present

**Comment by hombach** [comment]
0.2.0 released to NPM
