### ISSUE TITLE
feature request: add tmps data

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#32]
please add tmps data read from teslafi_API:

,"tpms_front_left":"43.1"
,"tpms_front_right":"43.5"
,"tpms_rear_left":"42.4"
,"tpms_rear_right":"43.1"

values are in PSI
maybe it´s possible to add them in psi and bar?

**Comment by hombach** [comment]
bar will be possible. 
What's the use case? sudden pressure loss while waiting in your garage? Wouldn't we get a message from Tesla APP in this case?

**Comment by Enno-von-Schwerin** [comment]
hmm,
pressure loss while sleeping wouldn´t be monitored, because while sleeping, no data will be send from teslafi_api

i think that was a wrong idea to be able to monitor like this
