### ISSUE TITLE
bug: aligning the value names

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#35]
**Describe the bug**  
names for values arenot aligned:
alle named: vehicle-data.....
except: driver_temp_setting and rawJSON

**Expected behavior**  
all names should have the same alignement

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/51b9ec81-2efe-44f7-abbb-cd9f96c33fa3)

**Versions:**
0.2.0

**Comment by hombach** [comment]
This had been fixed in 0.1.5 .... you have to delete all states - or the folder "vehicle-data" to get the states re-initialized.
Possible links or aliases are still working afterwards.

**Comment by Enno-von-Schwerin** [comment]
states deleted
bug is now fixed in my installation
