### ISSUE TITLE
Bug: speed should be set to 0 if null is send from teslafi

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#39]
**Describe the bug**  
teslafi will send speed=null, if the car is parked, charging or idling. or in other words, if it´s not in drive.

**To Reproduce**  
run car and if between last teslafi action and park is no more action from iobroker, then the last speed will be shown in value speed

**Expected behavior**  
speed should be 0 or null if car is not in drive

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/959913ed-891c-417d-9548-3e96096edea5)

left = iobroker
right = extract from teslafi JSON

**Versions:**
0.2.0

**Comment by hombach** [comment]
fixed in 0.2.1

**Comment by hombach** [comment]
0.2.1 released to NPM
