### ISSUE TITLE
Feature request: organize data in folders

### ISSUE THREAD

**Issue by hombach** [hombach/ioBroker.teslafi#43]
implement folder "car-state"; "battery-state"; "thermal-state" instead of having all in a single folder

**Comment by hombach** [comment]
implemented in 0.3.0

**Comment by hombach** [comment]
0.3.0 released to NPM

**Comment by Enno-von-Schwerin** [comment]
temperatures and seat / steering heating values are missing

inside temp
outside temp
hvac on/off
seat heating
stearing wheel heating
driver temp setting
