### ISSUE TITLE
bug: invalid time value

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#44]
**Describe the bug**  
since updateting to 0.3.0 the error:
invalid time value occures in log

**Screenshots & Logfiles**  
![image](https://github.com/user-attachments/assets/3b5a4f53-29db-42a1-80c3-07854e92d766)

**Versions:**
0.3.0

**Comment by hombach** [comment]
0.4.0 released to NPM
