### ISSUE TITLE
add value: NewVersionStatus

### ISSUE THREAD

**Issue by Enno-von-Schwerin** [hombach/ioBroker.teslafi#80]
please add the value NewVersionStatus according to NewVersion.

![grafik](https://github.com/user-attachments/assets/17dfadc6-d3b7-470e-a42c-b315679f0b87)

at the moment you are only reading
![grafik](https://github.com/user-attachments/assets/dd3e303a-dec4-49f3-a715-951ea3d05f3d)

**Comment by hombach** [comment]
released to beta repo as version 1.0.0
